silnti:
    resource: "@SilntiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
site:
    resource: "@SilntiBundle/Resources/config/routing.yml"
    prefix:    /