silnti:
    resource: "@SilntiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
site:
    resource: "@SilntiBundle/Resources/config/routing.yml"
    prefix:    /

_connexion:
    path: /connexion
    defaults: { _controller: SilntiBundle:Connexion:connexion }

_deconnexion:
    path: /deconnexion
    defaults: { _controller: SilntiBundle:Connexion:deconnexion }

_index:
    path: /
    defaults: { _controller: SilntiBundle:Default:index }

_gestionFichier:
    path: /gestionFichier
    defaults: { _controller: SilntiBundle:GestionFichier:gestionFichier }

_gestionPage:
    path: /gestionPage
    defaults: { _controller: SilntiBundle:GestionPage:gestionPage }

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

