silnti:
    resource: "@SilntiBundle/Controller/"
    type:     annotation
    prefix:   /

_connexion:
    path: /connexion
    defaults: { _controller: SilntiBundle:Connexion:connexion }

_index:
    path: /
    defaults: { _controller: SilntiBundle:Default:index }

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
